language: node_js
node_js:
  - "0.10"
before_install: "npm install -g npm && npm cache clean"
script: "npm run-script travis"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bce1a1b401d97fe096e2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
